tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autojump"
brew "fd"
brew "htop"
brew "krb5"
brew "luajit"
brew "luv"
brew "tree-sitter"
brew "neovim"
brew "node"
brew "postgresql", restart_service: true
brew "pyenv"
brew "ripgrep"
