tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autojump"
brew "fd"
brew "htop"
brew "neovim"
brew "postgresql", restart_service: true
brew "pyenv"
brew "ripgrep"
